/* Use cases: condensed from references/genres.md.
   Comparison: SKILL.md, references/boundaries.md, references/research-basis.md §A. */
export const USE={
en:[["Research papers","Cuts “In today's digital era” openers, keeps every citation exactly as given, and uses “significant” only with a test and a p-value."],["Reports","Summary first, numbers with units and periods, an owner and a date on every action item."],["Website copy","What it is, who it is for, what to do next. No invented testimonials, logos or stats."],["README & commits","Gets the reader unblocked fast. No “robust” or “seamless”, no emoji in commit logs unless the repo already uses them."],["Email","The subject states the ask, the first sentence says why you are writing, one request with a deadline."],["Video scripts","Written to be heard: short clauses, no citations read aloud, at most three items in a voice-over list."]],
id:[["Skripsi & jurnal","Membuang pembuka “Di era digital…”, menjaga setiap sitasi persis seperti aslinya, dan memakai “signifikan” hanya bila ada uji dan nilai p."],["Laporan","Ringkasan di depan, angka lengkap dengan satuan dan periode, penanggung jawab dan tenggat di setiap tindak lanjut."],["Copy website","Apa ini, untuk siapa, dan harus berbuat apa. Tanpa testimoni, logo, atau statistik karangan."],["README & commit","Supaya pembaca cepat lanjut bekerja. Tanpa “robust” atau “seamless”, tanpa emoji di log commit kecuali repo memakainya."],["Email","Subjek menyebut permintaan, kalimat pertama menyebut alasan, satu permintaan dengan tenggat."],["Naskah video","Ditulis untuk didengar: klausa pendek, sitasi tidak dibacakan, daftar di voice-over paling banyak tiga butir."]],
es:[["Artículos y tesis","Quita aperturas como “En la era digital actual”, conserva cada cita tal como está y usa “significativo” solo con una prueba y un valor p."],["Informes","Resumen primero, cifras con unidades y periodos, un responsable y una fecha en cada acción."],["Textos web","Qué es, para quién es y qué hacer. Sin testimonios, logos ni estadísticas inventados."],["README y commits","Que el lector avance rápido. Sin “robust” ni “seamless”, sin emoji en los commits salvo que el repositorio ya los use."],["Correo","El asunto dice lo que pides, la primera frase dice por qué escribes, una sola petición con fecha límite."],["Guiones de vídeo","Escritos para oírse: frases cortas, sin citas leídas en voz alta, como mucho tres elementos por lista en la locución."]],
ja:[["論文","「今日のデジタル時代において」のような書き出しを削り、引用は元のまま残し、「有意」は検定とp値がある場合だけ使います。"],["報告書","要約を先に。数値には単位と期間を、各対応事項には担当者と期日を付けます。"],["ウェブサイトの文章","何か、誰向けか、次に何をするか。架空の推薦文、ロゴ、統計は使いません。"],["READMEとコミット","読み手がすぐ作業を再開できるように。「robust」「seamless」は使わず、リポジトリの慣習でない限りコミットに絵文字を入れません。"],["メール","件名で用件を、最初の文で理由を伝え、依頼は期限付きで一つだけ。"],["動画の台本","聞かれるための文章：短い節、引用は読み上げず、ナレーションの列挙は3項目まで。"]],
zh:[["论文","删掉“在当今数字时代”式的开头，引用原样保留，“显著”只在有检验和 p 值时使用。"],["报告","先写摘要，数字带单位和时间段，每项行动都有负责人和日期。"],["网站文案","是什么、给谁用、下一步做什么。不编造推荐语、标志或数据。"],["README 与提交信息","让读者尽快继续工作。不用“robust”“seamless”，除非仓库惯例如此，提交日志不加表情符号。"],["邮件","主题写明请求，第一句说明来意，只提一个带截止日期的请求。"],["视频脚本","为听而写：短分句，不念引用，旁白中的列举最多三项。"]],
ms:[["Tesis & jurnal","Membuang pembuka “Dalam era digital…”, mengekalkan setiap petikan sumber seperti asal, dan menggunakan “signifikan” hanya jika ada ujian dan nilai p."],["Laporan","Ringkasan dahulu, angka dengan unit dan tempoh, pemilik dan tarikh pada setiap tindakan."],["Salinan laman web","Apa ini, untuk siapa, dan apa perlu dibuat. Tiada testimoni, logo atau statistik rekaan."],["README & commit","Supaya pembaca cepat menyambung kerja. Tiada “robust” atau “seamless”, tiada emoji dalam log commit melainkan repo sudah menggunakannya."],["E-mel","Subjek menyatakan permintaan, ayat pertama menyatakan sebab, satu permintaan dengan tarikh akhir."],["Skrip video","Ditulis untuk didengar: klausa pendek, petikan sumber tidak dibaca, senarai dalam suara latar paling banyak tiga perkara."]],
jv:[["Skripsi & jurnal","Mbuwang pambuka “Ing era digital…”, njaga saben sitasi persis kaya asline, lan nganggo “signifikan” mung yen ana uji lan nilai p."],["Laporan","Ringkesan ing ngarep, angka nganggo satuan lan periode, sing tanggung jawab lan tenggat ing saben tindak lanjut."],["Copy website","Iki apa, kanggo sapa, lan kudu ngapa. Tanpa testimoni, logo, utawa statistik gawean."],["README & commit","Supaya sing maca cepet bisa nyambut gawe maneh. Tanpa “robust” utawa “seamless”, tanpa emoji ing log commit kajaba repo wis nganggo."],["Email","Subjek nyebut panjaluk, ukara kapisan nyebut alesan, siji panjaluk karo tenggat."],["Naskah video","Ditulis supaya dirungokake: klausa cekak, sitasi ora diwaca, dhaptar ing voice-over paling akeh telu."]],
su:[["Skripsi & jurnal","Miceun bubuka “Di era digital…”, ngajaga unggal sitasi persis saperti aslina, sarta maké “signifikan” ngan lamun aya uji jeung nilai p."],["Laporan","Ringkesan di hareup, angka jeung satuan sarta période, nu tanggung jawab jeung wates waktu dina unggal tindak lanjut."],["Copy loka","Ieu naon, pikeun saha, jeung kudu ngalakukeun naon. Taya testimoni, logo, atawa statistik rékaan."],["README & commit","Sangkan nu maca gancang bisa digawé deui. Taya “robust” atawa “seamless”, taya émoji dina log commit iwal repo geus maké."],["Surélék","Subjék nyebut paménta, kalimah kahiji nyebut alesan, hiji paménta jeung wates waktuna."],["Naskah pidéo","Ditulis pikeun didéngé: klausa pondok, sitasi teu dibaca, daptar dina voice-over paling loba tilu."]],
ko:[["논문","“오늘날 디지털 시대에” 같은 서두를 지우고, 인용은 원문 그대로 두며, “유의미한”은 검정과 p값이 있을 때만 씁니다."],["보고서","요약을 먼저. 숫자에는 단위와 기간을, 모든 후속 조치에는 담당자와 날짜를 붙입니다."],["웹사이트 카피","무엇인지, 누구를 위한 것인지, 무엇을 하면 되는지. 지어낸 추천사, 로고, 통계는 없습니다."],["README와 커밋","읽는 사람이 바로 작업을 이어가도록. “robust”, “seamless”는 쓰지 않고, 저장소 관례가 아니면 커밋에 이모지를 넣지 않습니다."],["이메일","제목에 요청을, 첫 문장에 이유를 쓰고, 마감일이 있는 요청 하나만."],["영상 대본","듣기 위한 글: 짧은 절, 인용은 소리 내어 읽지 않고, 내레이션 나열은 세 개까지."]],
ar:[["الأبحاث والرسائل","تحذف افتتاحيات مثل «في العصر الرقمي الحالي»، وتُبقي كل استشهاد كما ورد، ولا تستخدم «دالّ إحصائياً» إلا مع اختبار وقيمة p."],["التقارير","الملخص أولاً، والأرقام بوحداتها وفتراتها، ومسؤول وتاريخ لكل إجراء."],["نصوص المواقع","ما هو، ولمن، وما الخطوة التالية. بلا شهادات أو شعارات أو إحصاءات مختلَقة."],["README ورسائل commit","ليعود القارئ إلى العمل بسرعة. بلا «robust» أو «seamless»، وبلا رموز تعبيرية في سجل commit ما لم يعتدها المستودع."],["البريد","الموضوع يذكر الطلب، والجملة الأولى تذكر السبب، وطلب واحد بموعد نهائي."],["نصوص الفيديو","مكتوبة لتُسمع: جمل قصيرة، ولا تُقرأ الاستشهادات بصوت عالٍ، وثلاثة عناصر على الأكثر في أي قائمة صوتية."]]};

export const CMP={
en:[["Ask “again” and get a different version every time.","One version in one pass. Three alternatives only if you ask."],["A missing figure gets filled with one that sounds right.","The gap is marked [figure?] or [fill: …]. Nothing is invented."],["Opens with “In today's fast-paced world”.","Starts with the point. On AI text the typical cut is 20–40% of words with no loss of meaning."],["Only words get swapped. The shape stays the same.","Texts over ~300 words get a seven-point structure pass. StoryScope: structure alone separates human and AI fiction at 93.2% macro-F1."],["Promises like “0% AI” or “passes Turnitin”.","No detector promises, no typos or hidden characters."]],
id:[["Minta “lagi” dan dapat versi baru setiap kali.","Satu versi dalam satu lintasan. Tiga alternatif hanya jika diminta."],["Data yang kosong diisi angka yang terdengar masuk akal.","Celah ditandai [angka?] atau [isi: …]. Tidak ada yang dikarang."],["Dibuka dengan “Di era digital yang semakin berkembang”.","Langsung ke inti. Pada teks AI biasanya 20–40% kata terbuang tanpa kehilangan makna."],["Hanya kata yang diganti, bentuk tulisan tetap sama.","Teks di atas ~300 kata melewati pemeriksaan struktur tujuh poin. StoryScope: fitur struktur saja membedakan fiksi manusia dan AI dengan macro-F1 93,2%."],["Janji semacam “lolos Turnitin” atau “0% AI”.","Tidak menjanjikan skor detektor, tidak menyisipkan typo atau karakter tersembunyi."]],
es:[["Pides “otra vez” y cada vez sale una versión distinta.","Una versión en una pasada. Tres alternativas solo si las pides."],["Un dato que falta se rellena con uno que suena bien.","El hueco se marca [¿cifra?] o [completar: …]. No se inventa nada."],["Empieza con “En el mundo acelerado de hoy”.","Empieza por lo importante. En texto de IA el recorte típico es del 20–40% de las palabras sin perder significado."],["Solo se cambian palabras. La forma sigue igual.","Los textos de más de ~300 palabras pasan una revisión de estructura de siete puntos. StoryScope: la estructura sola distingue ficción humana y de IA con 93,2% de macro-F1."],["Promesas como “0% IA” o “pasa Turnitin”.","Sin promesas sobre detectores, sin erratas ni caracteres ocultos."]],
ja:[["「もう一回」と頼むたびに別の版が出てくる。","一回の工程で一つの版。3案は頼まれたときだけ。"],["欠けた数値がもっともらしい数字で埋められる。","欠けた箇所は[数値?]や[記入: …]で示し、何も作りません。"],["「変化の激しい今日の世界において」で始まる。","要点から始めます。AIの文章では通常、意味を失わずに語数の20〜40%が削られます。"],["言葉を入れ替えるだけで、構成は変わらない。","約300語を超える文章には7項目の構成チェックを行います。StoryScope：構成だけで人間とAIのフィクションをmacro-F1 93.2%で区別。"],["「AI判定0%」「Turnitin通過」といった約束。","検出スコアは約束せず、誤字や隠し文字も入れません。"]],
zh:[["每说一次“再来”，就得到一个不同的版本。","一遍完成，只给一个版本。只有要求时才给三个备选。"],["缺的数字被填上一个听起来合理的数。","空缺标为 [数字?] 或 [填写: …]，不编造任何内容。"],["开头是“在当今快节奏的世界里”。","直接从要点开始。AI 文本通常可删去 20–40% 的字词而不损失意思。"],["只换词，结构不变。","超过约 300 词的文本要过一遍七点结构检查。StoryScope：仅凭结构就能以 93.2% 的 macro-F1 区分人类与 AI 写的小说。"],["承诺“0% AI”或“能过 Turnitin”。","不承诺检测分数，不插入错别字或隐藏字符。"]],
ms:[["Minta “lagi” dan dapat versi baharu setiap kali.","Satu versi dalam satu lintasan. Tiga alternatif hanya jika diminta."],["Data yang tiada diisi dengan angka yang kedengaran munasabah.","Jurang ditanda [angka?] atau [isi: …]. Tiada apa-apa direka."],["Dibuka dengan “Dalam dunia yang pantas berubah hari ini”.","Terus kepada isi. Pada teks AI biasanya 20–40% perkataan dibuang tanpa kehilangan makna."],["Hanya perkataan ditukar, bentuk tulisan kekal.","Teks melebihi ~300 perkataan melalui semakan struktur tujuh perkara. StoryScope: struktur sahaja membezakan fiksyen manusia dan AI pada macro-F1 93.2%."],["Janji seperti “0% AI” atau “lulus Turnitin”.","Tiada janji skor pengesan, tiada typo atau aksara tersembunyi."]],
jv:[["Njaluk “maneh” lan oleh versi anyar saben wektu.","Siji versi ing siji lintasan. Telung alternatif mung yen dijaluk."],["Data sing kosong diisi angka sing keprungu masuk akal.","Sing kosong ditandhani [angka?] utawa [isi: …]. Ora ana sing digawe-gawe."],["Dibukak nganggo “Ing era digital sing saya maju”.","Langsung menyang inti. Ing teks AI biasane 20–40% tembung dibuwang tanpa kelangan teges."],["Mung tembung sing diganti, wujude tetep.","Teks luwih saka ~300 tembung dipriksa strukture pitung poin. StoryScope: struktur wae bisa mbedakake fiksi manungsa lan AI kanthi macro-F1 93,2%."],["Janji kaya “0% AI” utawa “lolos Turnitin”.","Ora janji skor detektor, ora nyelipake typo utawa karakter singidan."]],
su:[["Ménta “deui” jeung meunang vérsi anyar unggal waktu.","Hiji vérsi dina hiji lintasan. Tilu alternatif ngan lamun dipénta."],["Data nu kosong dieusian angka nu kadéngé asup akal.","Nu kosong ditandaan [angka?] atawa [isi: …]. Taya nu dijieun-jieun."],["Dibuka ku “Di era digital nu beuki maju”.","Langsung kana inti. Dina téks AI biasana 20–40% kecap dipiceun tanpa leungit hartina."],["Ngan kecap nu diganti, wangunna tetep.","Téks leuwih ti ~300 kecap dipariksa strukturna tujuh poin. StoryScope: struktur wungkul bisa ngabédakeun fiksi manusa jeung AI dina macro-F1 93,2%."],["Jangji saperti “0% AI” atawa “lulus Turnitin”.","Teu jangji skor detéktor, teu nyelapkeun typo atawa karakter nyumput."]],
ko:[["“다시”라고 할 때마다 다른 버전이 나온다.","한 번에 한 버전. 대안 세 개는 요청할 때만."],["빠진 수치를 그럴듯한 숫자로 채운다.","빈 곳은 [수치?]나 [입력: …]로 표시합니다. 아무것도 지어내지 않습니다."],["“빠르게 변하는 오늘날의 세상에서”로 시작한다.","요점부터 시작합니다. AI 글은 보통 뜻을 잃지 않고 단어의 20–40%가 줄어듭니다."],["단어만 바뀌고 구조는 그대로다.","약 300단어가 넘는 글은 7가지 구조 점검을 거칩니다. StoryScope: 구조만으로 사람과 AI가 쓴 소설을 macro-F1 93.2%로 구분."],["“AI 0%”, “Turnitin 통과” 같은 약속.","탐지 점수를 약속하지 않고, 오타나 숨은 문자를 넣지 않습니다."]],
ar:[["تطلب «مرة أخرى» فتحصل على نسخة مختلفة كل مرة.","نسخة واحدة في تمريرة واحدة. ثلاثة بدائل فقط إن طلبتها."],["رقم ناقص يُملأ برقم يبدو معقولاً.","تُعلَّم الفجوة بـ [رقم؟] أو [أكمل: …]. لا يُختلق شيء."],["تبدأ بـ «في عالم اليوم سريع الإيقاع».","تبدأ بالفكرة. في نصوص الذكاء الاصطناعي يُحذف عادةً 20–40% من الكلمات دون فقدان المعنى."],["تُستبدل الكلمات فقط ويبقى الشكل كما هو.","النصوص التي تتجاوز ~300 كلمة تمرّ بفحص بنيوي من سبع نقاط. StoryScope: البنية وحدها تميّز القصص البشرية من قصص الذكاء الاصطناعي بمقياس macro-F1 قدره 93.2%."],["وعود مثل «0% ذكاء اصطناعي» أو «يتجاوز Turnitin».","لا وعود بدرجات كاشفات، ولا أخطاء إملائية أو محارف مخفية."]]};

/* Demo pairs, verbatim from examples/before-after-en.md and before-after-id.md.
   f = the phrases the demo flags; each must appear exactly in b. */
export const BAF={
en:[
{t:"Product update email",b:"Exciting news! 🎉 We're thrilled to announce a game-changing new feature that will revolutionize the way you manage your workflow. In today's fast-paced world, staying organized is more crucial than ever. That's why we've leveraged cutting-edge technology to seamlessly empower your team.",
 f:["Exciting news! 🎉","We're thrilled to announce","game-changing","revolutionize the way you manage your workflow","In today's fast-paced world","more crucial than ever","leveraged cutting-edge technology","seamlessly empower your team"],
 a:"You can now assign a task to two people. Both see it in their queue, and it closes when either one marks it done. It's live for all workspaces today."},
{t:"README intro",b:"This robust and powerful library provides a comprehensive, seamless solution for handling dates in JavaScript, empowering developers to unlock the full potential of their applications.",
 f:["robust and powerful","comprehensive, seamless solution","empowering developers to unlock the full potential of their applications"],
 a:"Parse, format, and compare dates in JavaScript. 4 KB, no dependencies.\nnpm install tinydate"},
{t:"Report summary",b:"Overall, the quarter was marked by significant progress across multiple key areas, underscoring the team's commitment to excellence and paving the way for continued growth.",
 f:["Overall,","significant progress across multiple key areas","underscoring the team's commitment to excellence","paving the way for continued growth"],
 a:"Q3 revenue was $1.2M, up 18% from Q2. Churn fell from 4.1% to 3.3%. The EU launch slipped to November because of the payments vendor; we need a decision on the backup vendor by Oct 1."}],
id:[
{t:"Laporan penelitian",b:"Di era digital yang semakin berkembang pesat seperti sekarang ini, tidak dapat dipungkiri bahwa teknologi informasi memiliki peran yang sangat penting dalam berbagai aspek kehidupan, termasuk dalam dunia pendidikan. Pemanfaatan teknologi secara optimal dapat memberikan dampak yang signifikan terhadap peningkatan kualitas pembelajaran secara keseluruhan.",
 f:["Di era digital yang semakin berkembang pesat seperti sekarang ini","tidak dapat dipungkiri bahwa","memiliki peran yang sangat penting","dalam berbagai aspek kehidupan","secara optimal","dampak yang signifikan","secara keseluruhan"],
 a:"Sejak 2020, sekolah di Indonesia makin bergantung pada platform pembelajaran daring. Namun, bukti tentang pengaruhnya terhadap hasil belajar siswa SMA masih terbatas [sitasi?]. Penelitian ini mengukur hubungan antara frekuensi penggunaan LMS dan nilai ujian akhir di tiga SMA negeri di Kota Malang."},
{t:"Copy website",b:"Selamat datang di KasirKu! Kami hadir sebagai solusi inovatif dan komprehensif untuk membantu mengoptimalkan bisnis Anda di era digital. Dengan fitur-fitur canggih yang mudah digunakan, KasirKu siap menjadi partner terbaik Anda! 🚀",
 f:["Selamat datang di KasirKu!","solusi inovatif dan komprehensif","mengoptimalkan","di era digital","fitur-fitur canggih yang mudah digunakan","siap menjadi partner terbaik Anda!","🚀"],
 a:"Stok, kasir, dan laporan harian dalam satu aplikasi.\nKasirKu mencatat setiap transaksi dan mengurangi stok otomatis, jadi Anda tahu barang mana yang perlu dipesan sebelum habis.\n[Coba gratis 14 hari]"},
{t:"Pamflet acara",b:"Yuk ikuti seminar spektakuler yang akan membuka wawasan kalian tentang dunia kewirausahaan secara mendalam dan menyeluruh bersama para pembicara hebat dan inspiratif!!!",
 f:["Yuk ikuti seminar spektakuler","membuka wawasan kalian","secara mendalam dan menyeluruh","para pembicara hebat dan inspiratif!!!"],
 a:"Seminar: Memulai Usaha dengan Modal di Bawah 5 Juta\nSabtu, 12 Oktober 2026 · 09.00–12.00 WIB\nAula Gedung B, Universitas [isi]\nGratis · Daftar: [link/QR]"}]};
