/* StoryScope (Russell et al., arXiv:2604.03136v6, COLM 2026), Table 16 and Table 17.
   Values are the paper's: % = share of stories, /5 = Likert mean, ord = ordinal mean.
   Feature labels exist in en and id; other languages fall back to en. */

export const THEMES = [
  { k: "over", side: "ai", rows: [
    ["Thematic explicitness & moralizing", "Tema dan moral dinyatakan terang", 3.28, 3.94, "/5"],
    ["Moral/philosophical weighting", "Bobot pertanyaan moral", 3.26, 3.68, "/5"],
    ["Thematic unity", "Semua subplot melayani satu tema", 4.41, 4.74, "/5"],
    ["Narrator comments on the theme", "Narator mengomentari tema", 52, 77, "%"],
    ["Dialogue used as philosophical debate", "Dialog dipakai untuk berdebat ide", 34, 59, "%"],
    ["References are vague echoes", "Rujukan berupa gema samar", 50, 72, "%"] ] },
  { k: "body", side: "ai", rows: [
    ["Emotion shown through the body", "Emosi lewat tubuh", 38, 81, "%"],
    ["Setting mirrors the mood", "Latar mencerminkan suasana hati", 3.58, 4.07, "/5"],
    ["Environmental emphasis", "Penekanan lingkungan alam", 2.83, 3.21, "/5"],
    ["Uses smell", "Memakai indra penciuman", 57, 82, "%"],
    ["Sensory density", "Kepadatan deskripsi indrawi", 3.66, 3.93, "/5"],
    ["Depth of interior access", "Kedalaman akses ke batin", 3.67, 3.93, "/5"] ] },
  { k: "tidy", side: "ai", rows: [
    ["One continuous causal chain", "Satu rantai sebab-akibat utuh", 3.92, 4.20, "/5"],
    ["Resolved by the hero's choice", "Diselesaikan oleh pilihan tokoh utama", 46, 69, "%"],
    ["Hero introduced by description", "Tokoh diperkenalkan lewat deskripsi", 30, 52, "%"],
    ["No subplots", "Tanpa subplot", 57, 79, "%"],
    ["Resolved by inner acceptance", "Selesai lewat penerimaan batin", 27, 47, "%"],
    ["Long warm-up before the threat", "Pemanasan panjang sebelum ancaman", 2.76, 2.99, "/5"] ] },
  { k: "world", side: "human", rows: [
    ["Names a specific work", "Menyebut karya tertentu", 47, 24, "%"],
    ["Mix of explicit and implicit references", "Campuran rujukan terang dan samar", 37, 16, "%"],
    ["Breaks the fourth wall", "Menembus dinding keempat", 67, 39, "%"],
    ["Addresses the reader", "Menyapa pembaca", 28, 7, "%"] ] },
  { k: "time", side: "human", rows: [
    ["A reveal rereads earlier scenes", "Pengungkapan mengubah adegan awal", 3.28, 2.95, "/5"],
    ["Chronological discontinuity", "Loncatan waktu", 2.40, 2.12, "/5"],
    ["Nonlinear framing to delay disclosure", "Alur tak linear untuk menunda", 1.96, 1.68, "/5"],
    ["Flashbacks and flash-forwards", "Kilas balik dan kilas depan", 2.58, 2.31, "/5"] ] },
  { k: "range", side: "human", rows: [
    ["Subplots echo the main line", "Subplot sejajar dengan tema", 42, 21, "%"],
    ["Morally ambivalent protagonist", "Tokoh utama ambivalen secara moral", 59, 38, "%"],
    ["Emotion named plainly", "Emosi disebut langsung", 29, 8, "%"],
    ["Dialogue share of the text", "Porsi dialog", 2.95, 2.70, "/5"] ] },
];

export const FP = {
  Claude: { f1: 0.77, n: 26, en: ["Flattest event escalation of any source", "Low variety of event types", "Ends with an epilogue or a jump forward", "No dreams or visions", "Honours tradition: 62% vs 39–56%"], id: ["Eskalasi peristiwa paling datar", "Jenis peristiwa kurang beragam", "Berakhir dengan epilog atau lompatan ke depan", "Tanpa mimpi atau penglihatan", "Menghormati tradisi: 62% vs 39–56%"] },
  GPT: { f1: 0.73, n: 11, en: ["Gossip and rumour drive the plot: 64% vs 44–55%", "Narrator looks back across years", "Subverts expectations: 41% vs 27–36%", "Reconciliations left ambiguous", "Ensemble casts"], id: ["Gosip dan rumor menggerakkan plot: 64% vs 44–55%", "Narator menoleh ke masa bertahun-tahun lalu", "Membalik harapan: 41% vs 27–36%", "Rekonsiliasi dibiarkan ambigu", "Banyak tokoh setara"] },
  Gemini: { f1: 0.60, n: 11, en: ["Bleakest settings: 88% bleak or oppressive", "Tidiest endings, long denouements", "Siege or ordeal story shape", "Characters described from outside", "Frequent flashbacks"], id: ["Latar paling suram: 88% suram atau menekan", "Akhir paling rapi, penutup panjang", "Pola cerita pengepungan atau cobaan", "Tokoh digambarkan dari luar", "Sering kilas balik"] },
  DeepSeek: { f1: 0.57, n: 7, en: ["Front-loads crucial context", "Backstory evenly interleaved", "Visible narrator", "Emotion through behaviour", "Stories within the story"], id: ["Konteks penting ditumpuk di depan", "Latar belakang disisipkan merata", "Narator terlihat", "Emosi lewat perilaku", "Cerita di dalam cerita"] },
  Kimi: { f1: 0.55, n: 3, en: ["Characters introduced in action", "Opens in medias res", "Avoids explicit trait labels", "Otherwise the generic centre"], id: ["Tokoh diperkenalkan saat beraksi", "Dibuka di tengah peristiwa", "Menghindari label sifat eksplisit", "Selebihnya pusat yang generik"] },
  Human: { f1: 0.89, n: 32, en: ["Characters arrive talking", "One focal character", "Revelations back-loaded", "Crossover-genre ambition", "Rarest version of its prompt 57.8% of the time"], id: ["Tokoh muncul sambil berbicara", "Satu tokoh fokal", "Pengungkapan ditaruh di belakang", "Ambisi lintas genre", "Versi paling langka dari promptnya 57,8% kali"] },
};

/* Section strings for all ten languages. */
export const S = {
en: { nav: "Structure", h: "The layer under the words", p: "Sixty-one thousand stories, one human and five models per prompt. With every word-level clue removed, structure alone still told them apart 93.2% of the time. These are the habits it measured. Lugas checks your draft against all of them.", human: "Human", ai: "AI", aiLean: "AI leans here", humanLean: "Humans lean here", fpH: "Each model has a signature", fpP: "Per-source F1 on narrative features alone, and the top habits the paper found.", fpN: "signature features", note: "Source: Russell et al., StoryScope, arXiv:2604.03136v6 (COLM 2026), Tables 12, 16, 17. Bar length compares the two numbers in each row.", themes: { over: "Over-explaining", body: "Body & senses", tidy: "Tidy plots", world: "The outside world", time: "Time", range: "Range" }, stats: ["stories compared", "detected from structure alone", "core structural habits", "annotated sources"], famH: "Four skills, one standard", famP: "Each does one job and hands off to the next. All plain Markdown, all free.", fam: [["lugas", "Plain, specific prose. Removes filler, then fixes the structure underneath."], ["rangka", "The outline before any paragraph: who reads it, what each section must prove."], ["pedoman", "Format compliance, clause by clause, for twelve Indonesian universities and five abroad."], ["atmajaya", "The whole road for UAJM students: KKP, proposal, skripsi, sidang."]] },
id: { nav: "Struktur", h: "Lapisan di bawah kata-kata", p: "Enam puluh satu ribu cerita, satu versi manusia dan lima versi model untuk tiap prompt. Setelah semua petunjuk tingkat kata dibuang, struktur saja masih membedakan keduanya 93,2% kali. Inilah kebiasaan yang diukur. Lugas memeriksa draf Anda terhadap semuanya.", human: "Manusia", ai: "AI", aiLean: "AI condong ke sini", humanLean: "Manusia condong ke sini", fpH: "Tiap model punya tanda tangan", fpP: "F1 per sumber dari fitur naratif saja, dan kebiasaan teratas yang ditemukan makalah.", fpN: "fitur penanda", note: "Sumber: Russell dkk., StoryScope, arXiv:2604.03136v6 (COLM 2026), Tabel 12, 16, 17. Panjang batang membandingkan dua angka di tiap baris.", themes: { over: "Terlalu menjelaskan", body: "Tubuh & indra", tidy: "Plot rapi", world: "Dunia luar", time: "Waktu", range: "Keragaman" }, stats: ["cerita dibandingkan", "terdeteksi dari struktur saja", "kebiasaan struktural inti", "sumber beranotasi"], famH: "Empat skill, satu standar", famP: "Masing-masing mengerjakan satu tugas lalu menyerahkan ke yang berikutnya. Semuanya Markdown biasa, semuanya gratis.", fam: [["lugas", "Prosa yang lugas dan spesifik. Membuang basa-basi, lalu membenahi struktur di bawahnya."], ["rangka", "Kerangka sebelum paragraf pertama: siapa pembacanya, apa yang harus dibuktikan tiap bagian."], ["pedoman", "Kepatuhan format per klausul untuk dua belas kampus Indonesia dan lima kampus luar negeri."], ["atmajaya", "Seluruh jalan mahasiswa UAJM: KKP, proposal, skripsi, sidang."]] },
es: { nav: "Estructura", h: "La capa bajo las palabras", p: "Sesenta y un mil relatos, uno humano y cinco de modelos por cada consigna. Sin ninguna pista de vocabulario, la estructura sola los distinguió el 93,2% de las veces. Estos son los hábitos medidos. Lugas revisa tu borrador frente a todos.", human: "Humano", ai: "IA", aiLean: "La IA tiende aquí", humanLean: "Los humanos tienden aquí", fpH: "Cada modelo tiene una firma", fpP: "F1 por fuente solo con rasgos narrativos, y los hábitos principales del artículo.", fpN: "rasgos de firma", note: "Fuente: Russell et al., StoryScope, arXiv:2604.03136v6 (COLM 2026), tablas 12, 16 y 17. La barra compara los dos números de cada fila.", themes: { over: "Explicar de más", body: "Cuerpo y sentidos", tidy: "Tramas ordenadas", world: "El mundo exterior", time: "Tiempo", range: "Variedad" }, stats: ["relatos comparados", "detectados solo por estructura", "hábitos estructurales clave", "fuentes anotadas"], famH: "Cuatro skills, un criterio", famP: "Cada una hace un trabajo y pasa a la siguiente. Todo Markdown, todo gratis.", fam: [["lugas", "Prosa clara y concreta. Quita el relleno y luego arregla la estructura."], ["rangka", "El esquema antes del primer párrafo: quién lee y qué debe probar cada sección."], ["pedoman", "Formato cláusula por cláusula para doce universidades indonesias y cinco extranjeras."], ["atmajaya", "Todo el camino para estudiantes de la UAJM: prácticas, propuesta, tesis, defensa."]] },
ja: { nav: "構造", h: "言葉の下にある層", p: "1つのお題につき人間1本とモデル5本、計6万1千本の物語。語彙の手がかりをすべて除いても、構造だけで93.2%の確率で見分けられました。測定された癖はこれです。Lugasは下書きをすべてに照らして確認します。", human: "人間", ai: "AI", aiLean: "AIに多い", humanLean: "人間に多い", fpH: "モデルごとの署名", fpP: "物語的特徴のみでのソース別F1と、論文が見つけた主な癖。", fpN: "署名となる特徴", note: "出典：Russell ほか, StoryScope, arXiv:2604.03136v6（COLM 2026）表12・16・17。棒の長さは各行の2つの数値を比べたものです。", themes: { over: "説明しすぎ", body: "身体と感覚", tidy: "整いすぎた筋", world: "外の世界", time: "時間", range: "幅" }, stats: ["比較した物語", "構造だけで判別", "中核となる構造の癖", "注釈付き文献"], famH: "4つのスキル、ひとつの基準", famP: "それぞれが1つの仕事をして次へ渡します。すべてMarkdown、すべて無料。", fam: [["lugas", "簡潔で具体的な文章。水増しを削り、その下の構造を直します。"], ["rangka", "最初の段落の前に骨組みを。誰が読み、各節が何を示すべきか。"], ["pedoman", "インドネシア12大学と海外5機関の書式を条項ごとに確認。"], ["atmajaya", "UAJMの学生のための全行程：インターン、計画書、卒論、口頭試問。"]] },
zh: { nav: "结构", h: "文字之下的那一层", p: "六万一千篇故事，每个题目一篇人类作品和五篇模型作品。去掉所有词汇层面的线索后，仅凭结构仍有93.2%的概率区分二者。以下是被测量出的习惯。Lugas 会用它们逐一检查你的草稿。", human: "人类", ai: "AI", aiLean: "AI 偏向这里", humanLean: "人类偏向这里", fpH: "每个模型都有签名", fpP: "仅用叙事特征时各来源的 F1，以及论文发现的主要习惯。", fpN: "签名特征", note: "来源：Russell 等，StoryScope，arXiv:2604.03136v6（COLM 2026），表 12、16、17。条形长度比较每行的两个数字。", themes: { over: "过度解释", body: "身体与感官", tidy: "整齐的情节", world: "外部世界", time: "时间", range: "多样性" }, stats: ["篇故事对比", "仅凭结构识别", "项核心结构习惯", "条注释文献"], famH: "四个技能，一个标准", famP: "各做一件事，再交给下一个。全部是 Markdown，全部免费。", fam: [["lugas", "平实、具体的文字。先删废话，再修正下面的结构。"], ["rangka", "写第一段之前先搭框架：谁来读，每一节要证明什么。"], ["pedoman", "按条款检查格式，覆盖十二所印尼大学和五所海外院校。"], ["atmajaya", "UAJM 学生的全程：实习、开题、毕业论文、答辩。"]] },
ms: { nav: "Struktur", h: "Lapisan di bawah perkataan", p: "Enam puluh satu ribu cerita, satu manusia dan lima model bagi setiap gesaan. Tanpa sebarang petunjuk perkataan, struktur sahaja masih membezakannya 93.2% kali. Inilah tabiat yang diukur. Lugas menyemak draf anda terhadap semuanya.", human: "Manusia", ai: "AI", aiLean: "AI cenderung di sini", humanLean: "Manusia cenderung di sini", fpH: "Setiap model ada tandatangan", fpP: "F1 setiap sumber daripada ciri naratif sahaja, dan tabiat utama yang ditemui kertas itu.", fpN: "ciri tandatangan", note: "Sumber: Russell et al., StoryScope, arXiv:2604.03136v6 (COLM 2026), Jadual 12, 16, 17. Panjang bar membandingkan dua nombor dalam setiap baris.", themes: { over: "Terlebih jelas", body: "Tubuh & deria", tidy: "Plot kemas", world: "Dunia luar", time: "Masa", range: "Kepelbagaian" }, stats: ["cerita dibandingkan", "dikesan daripada struktur sahaja", "tabiat struktur teras", "sumber beranotasi"], famH: "Empat skill, satu piawai", famP: "Setiap satu membuat satu kerja dan menyerahkan kepada yang seterusnya. Semuanya Markdown, semuanya percuma.", fam: [["lugas", "Prosa yang jelas dan khusus. Membuang isian, kemudian membaiki struktur."], ["rangka", "Rangka sebelum perenggan pertama: siapa pembaca, apa yang mesti dibuktikan setiap bahagian."], ["pedoman", "Pematuhan format mengikut klausa untuk dua belas universiti Indonesia dan lima di luar negara."], ["atmajaya", "Seluruh perjalanan pelajar UAJM: latihan industri, cadangan, tesis, sidang."]] },
jv: { nav: "Struktur", h: "Lapisan ing sangisore tembung", p: "Sewidak siji ewu crita, siji manungsa lan lima model saben prompt. Sawise kabeh pitunjuk tembung dibuwang, struktur wae isih bisa mbedakake 93,2% kaping. Iki pakulinan sing diukur. Lugas mriksa draf panjenengan nganggo kabeh iki.", human: "Manungsa", ai: "AI", aiLean: "AI luwih kerep ing kene", humanLean: "Manungsa luwih kerep ing kene", fpH: "Saben model duwe tandha", fpP: "F1 saben sumber saka fitur narasi wae, lan pakulinan utama sing ditemokake makalah.", fpN: "fitur tandha", note: "Sumber: Russell lsp., StoryScope, arXiv:2604.03136v6 (COLM 2026), Tabel 12, 16, 17. Dawane bar mbandhingake angka loro ing saben baris.", themes: { over: "Kakehan nerangake", body: "Awak & indra", tidy: "Plot rapi", world: "Donya njaba", time: "Wektu", range: "Warna-warni" }, stats: ["crita dibandhingake", "ketemu saka struktur wae", "pakulinan struktur inti", "sumber anotasi"], famH: "Papat skill, siji standar", famP: "Saben siji nindakake siji gawean banjur diterusake. Kabeh Markdown, kabeh gratis.", fam: [["lugas", "Tulisan sing lugas lan spesifik. Mbuwang basa-basi, banjur ndandani strukture."], ["rangka", "Kerangka sadurunge paragraf kapisan: sapa sing maca, apa sing kudu dibuktekake."], ["pedoman", "Format miturut klausul kanggo rolas kampus Indonesia lan lima kampus manca."], ["atmajaya", "Dalan jangkep kanggo mahasiswa UAJM: KKP, proposal, skripsi, sidang."]] },
su: { nav: "Struktur", h: "Lapisan di handapeun kecap", p: "Genep puluh hiji rébu carita, hiji manusa jeung lima modél pikeun unggal prompt. Sanggeus sakabéh tanda kecap dipiceun, struktur wungkul masih ngabédakeun 93,2% kali. Ieu kabiasaan anu diukur. Lugas mariksa draf anjeun kana sadayana.", human: "Manusa", ai: "AI", aiLean: "AI condong ka dieu", humanLean: "Manusa condong ka dieu", fpH: "Unggal modél boga tanda", fpP: "F1 unggal sumber tina fitur naratif wungkul, jeung kabiasaan utama anu kapanggih.", fpN: "fitur tanda", note: "Sumber: Russell spk., StoryScope, arXiv:2604.03136v6 (COLM 2026), Tabel 12, 16, 17. Panjang bar ngabandingkeun dua angka dina unggal baris.", themes: { over: "Kaleuleuwihi ngajelaskeun", body: "Awak & indra", tidy: "Plot rapih", world: "Dunya luar", time: "Waktu", range: "Rupa-rupa" }, stats: ["carita dibandingkeun", "kapanggih tina struktur wungkul", "kabiasaan struktur inti", "sumber anotasi"], famH: "Opat skill, hiji standar", famP: "Masing-masing ngerjakeun hiji pagawéan tuluy dipasrahkeun ka nu salajengna. Sadayana Markdown, sadayana gratis.", fam: [["lugas", "Tulisan anu lugas jeung spésifik. Miceun basa-basi, tuluy ngomean strukturna."], ["rangka", "Kerangka saméméh paragraf kahiji: saha nu maca, naon nu kudu dibuktikeun."], ["pedoman", "Format per klausul pikeun dua belas kampus Indonésia jeung lima kampus luar nagri."], ["atmajaya", "Jalan lengkep pikeun mahasiswa UAJM: KKP, proposal, skripsi, sidang."]] },
ko: { nav: "구조", h: "단어 아래의 층", p: "프롬프트마다 사람 1편과 모델 5편, 모두 6만 1천 편의 이야기. 단어 수준의 단서를 모두 지워도 구조만으로 93.2%를 구별했습니다. 측정된 습관은 다음과 같습니다. Lugas는 초안을 이 모두에 비추어 점검합니다.", human: "사람", ai: "AI", aiLean: "AI 쪽에 많음", humanLean: "사람 쪽에 많음", fpH: "모델마다 서명이 있다", fpP: "서사 특징만 쓴 출처별 F1과 논문이 찾은 주요 습관.", fpN: "서명 특징", note: "출처: Russell 외, StoryScope, arXiv:2604.03136v6 (COLM 2026), 표 12·16·17. 막대 길이는 각 행의 두 숫자를 비교합니다.", themes: { over: "과한 설명", body: "몸과 감각", tidy: "깔끔한 플롯", world: "바깥 세계", time: "시간", range: "다양성" }, stats: ["편의 이야기 비교", "구조만으로 판별", "핵심 구조 습관", "주석 달린 출처"], famH: "네 개의 스킬, 하나의 기준", famP: "각자 한 가지 일을 하고 다음으로 넘깁니다. 모두 Markdown, 모두 무료.", fam: [["lugas", "평이하고 구체적인 글. 군더더기를 걷어내고 그 아래 구조를 고칩니다."], ["rangka", "첫 문단 전에 뼈대: 누가 읽고 각 절이 무엇을 증명해야 하는지."], ["pedoman", "인도네시아 12개 대학과 해외 5개 기관의 서식을 조항별로 점검."], ["atmajaya", "UAJM 학생의 전 과정: 현장실습, 제안서, 졸업논문, 심사."]] },
ar: { nav: "البنية", h: "الطبقة التي تحت الكلمات", p: "واحد وستون ألف قصة، واحدة بشرية وخمس من النماذج لكل موضوع. بعد حذف كل دليل على مستوى الكلمات، ميّزت البنية وحدها بينها في 93.2% من الحالات. هذه هي العادات التي قيست. يفحص Lugas مسودتك مقابلها جميعًا.", human: "بشري", ai: "ذكاء اصطناعي", aiLean: "يميل إليها الذكاء الاصطناعي", humanLean: "يميل إليها البشر", fpH: "لكل نموذج توقيع", fpP: "مقياس F1 لكل مصدر من السمات السردية وحدها، وأبرز العادات التي وجدتها الورقة.", fpN: "سمات مميِّزة", note: "المصدر: Russell وآخرون، StoryScope، arXiv:2604.03136v6 (COLM 2026)، الجداول 12 و16 و17. طول الشريط يقارن الرقمين في كل صف.", themes: { over: "الإفراط في الشرح", body: "الجسد والحواس", tidy: "حبكات مرتّبة", world: "العالم الخارجي", time: "الزمن", range: "التنوع" }, stats: ["قصة قورنت", "كُشفت من البنية وحدها", "عادات بنيوية أساسية", "مصدرًا مشروحًا"], famH: "أربع مهارات، معيار واحد", famP: "كل واحدة تؤدي عملًا واحدًا ثم تسلّم التالية. كلها Markdown، وكلها مجانية.", fam: [["lugas", "نثر واضح ومحدد. يحذف الحشو ثم يصلح البنية تحته."], ["rangka", "الهيكل قبل الفقرة الأولى: من يقرأ، وما الذي يجب أن يثبته كل قسم."], ["pedoman", "مطابقة التنسيق بندًا بندًا لاثنتي عشرة جامعة إندونيسية وخمس مؤسسات خارجها."], ["atmajaya", "الطريق كاملًا لطلاب UAJM: التدريب، المقترح، الرسالة، المناقشة."]] },
};
